<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BljtxGn' shared service.

return $this->privates['.service_locator.BljtxGn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'category' => ['privates', '.errored..service_locator.BljtxGn.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.BljtxGn": it references class "App\\Entity\\Category" but no such service exists.'],
], [
    'category' => 'App\\Entity\\Category',
]);
