<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vpqrZBs' shared service.

return $this->privates['.service_locator.vpqrZBs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ArticleController::delete' => ['privates', '.service_locator.WKL2avN', 'get_ServiceLocator_WKL2avNService.php', true],
    'App\\Controller\\ArticleController::edit' => ['privates', '.service_locator.WKL2avN', 'get_ServiceLocator_WKL2avNService.php', true],
    'App\\Controller\\ArticleController::index' => ['privates', '.service_locator.Dx03tsO', 'get_ServiceLocator_Dx03tsOService.php', true],
    'App\\Controller\\ArticleController::index2' => ['privates', '.service_locator.Dx03tsO', 'get_ServiceLocator_Dx03tsOService.php', true],
    'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.WKL2avN', 'get_ServiceLocator_WKL2avNService.php', true],
    'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.BljtxGn', 'get_ServiceLocator_BljtxGnService.php', true],
    'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.BljtxGn', 'get_ServiceLocator_BljtxGnService.php', true],
    'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.CvFKf6j', 'get_ServiceLocator_CvFKf6jService.php', true],
    'App\\Controller\\CategoryController::index2' => ['privates', '.service_locator.lbrMl4P', 'get_ServiceLocator_LbrMl4PService.php', true],
    'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.BljtxGn', 'get_ServiceLocator_BljtxGnService.php', true],
    'App\\Controller\\ArticleController:delete' => ['privates', '.service_locator.WKL2avN', 'get_ServiceLocator_WKL2avNService.php', true],
    'App\\Controller\\ArticleController:edit' => ['privates', '.service_locator.WKL2avN', 'get_ServiceLocator_WKL2avNService.php', true],
    'App\\Controller\\ArticleController:index' => ['privates', '.service_locator.Dx03tsO', 'get_ServiceLocator_Dx03tsOService.php', true],
    'App\\Controller\\ArticleController:index2' => ['privates', '.service_locator.Dx03tsO', 'get_ServiceLocator_Dx03tsOService.php', true],
    'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.WKL2avN', 'get_ServiceLocator_WKL2avNService.php', true],
    'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.BljtxGn', 'get_ServiceLocator_BljtxGnService.php', true],
    'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.BljtxGn', 'get_ServiceLocator_BljtxGnService.php', true],
    'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.CvFKf6j', 'get_ServiceLocator_CvFKf6jService.php', true],
    'App\\Controller\\CategoryController:index2' => ['privates', '.service_locator.lbrMl4P', 'get_ServiceLocator_LbrMl4PService.php', true],
    'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.BljtxGn', 'get_ServiceLocator_BljtxGnService.php', true],
], [
    'App\\Controller\\ArticleController::delete' => '?',
    'App\\Controller\\ArticleController::edit' => '?',
    'App\\Controller\\ArticleController::index' => '?',
    'App\\Controller\\ArticleController::index2' => '?',
    'App\\Controller\\ArticleController::show' => '?',
    'App\\Controller\\CategoryController::delete' => '?',
    'App\\Controller\\CategoryController::edit' => '?',
    'App\\Controller\\CategoryController::index' => '?',
    'App\\Controller\\CategoryController::index2' => '?',
    'App\\Controller\\CategoryController::show' => '?',
    'App\\Controller\\ArticleController:delete' => '?',
    'App\\Controller\\ArticleController:edit' => '?',
    'App\\Controller\\ArticleController:index' => '?',
    'App\\Controller\\ArticleController:index2' => '?',
    'App\\Controller\\ArticleController:show' => '?',
    'App\\Controller\\CategoryController:delete' => '?',
    'App\\Controller\\CategoryController:edit' => '?',
    'App\\Controller\\CategoryController:index' => '?',
    'App\\Controller\\CategoryController:index2' => '?',
    'App\\Controller\\CategoryController:show' => '?',
]);
