<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.WKL2avN.App\Entity\Article' shared service.

$this->throw('Cannot autowire service ".service_locator.WKL2avN": it references class "App\\Entity\\Article" but no such service exists.');
